### ISSUE TITLE
Internal Server error when running the Patch API Sample

### ISSUE THREAD

**Issue by ssrikantan** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#16]
When I run the .NET sample, It always throws an internal server error
----
1.6 - Patching a item using its Id
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 57d0ab61-59df-4fac-aa10-bf8259d3d28f; Reason: (Message: {"Errors":["An unknown error occurred while processing this request. If the issue persists, please contact Azure Support: http://aka.ms/azure-support"]}
 ----
Is it possible for me to run a command to check if this private preview is indeed enabled on my account? Or am I missing something

**Comment by saawasek** [comment]
@ssrikantan (Pasting the same reply :) 
Thanks for trying out Patch API. For your Database account: “divprocessing”,  Patch is already enabled.
Now since we are in Private Preview, for any newly created collection, Patch gets enabled on this collection after 5 mins from the time of create.
This won’t happen in GA as it would be enabled by default.

I see that you are trying Create_Collection->Patch_Item->Delete. By the time Patch API comes, it’s not effectively enabled(due to 5 mins delay). 
So if you try Patching an existing Collection, it should work or add a delay on creating a new one.

Thanks,
Sameer

**Comment by ssrikantan** [comment]
thanks. yes, I retained the collection without deleting, and it worked as expected
